set mapreduce.map.memory.mb=4000;
set mapreduce.reduce.memory.mb=4000;
SET mapred.child.java.opts=-Xmx4G -XX:+UseConcMarkSweepGC;
SET mapred.reduce.tasks=112;

use mrqos;
SET hive.cli.print.header=true;

SELECT
 c.*,
 (cast(c.sp99 as DOUBLE) * b.Cosine2) sp99_real_2,
 (cast(c.sp99 as DOUBLE) * b.Sine2) sp99_imag_2,
 (cast(c.sp95 as DOUBLE) * b.Cosine2) sp95_real_2,
 (cast(c.sp95 as DOUBLE) * b.Sine2) sp95_imag_2,
 (cast(c.sp90 as DOUBLE) * b.Cosine2) sp90_real_2,
 (cast(c.sp90 as DOUBLE) * b.Sine2) sp90_imag_2,
 (cast(c.sp75 as DOUBLE) * b.Cosine2) sp75_real_2,
 (cast(c.sp75 as DOUBLE) * b.Sine2) sp75_imag_2,
 (cast(c.dp99 as DOUBLE) * b.Cosine2) dp99_real_2,
 (cast(c.dp99 as DOUBLE) * b.Sine2) dp99_imag_2,
 (cast(c.dp95 as DOUBLE) * b.Cosine2) dp95_real_2,
 (cast(c.dp95 as DOUBLE) * b.Sine2) dp95_imag_2,
 (cast(c.dp90 as DOUBLE) * b.Cosine2) dp90_real_2,
 (cast(c.dp90 as DOUBLE) * b.Sine2) dp90_imag_2,
 (cast(c.dp75 as DOUBLE) * b.Cosine2) dp75_real_2,
 (cast(c.dp75 as DOUBLE) * b.Sine2) dp75_imag_2,
 (cast(c.icy_pct as DOUBLE) * b.Cosine2) icy_real_2,
 (cast(c.icy_pct as DOUBLE) * b.Sine2) icy_imag_2,
 (cast(c.ict_pct as DOUBLE) * b.Cosine2) ict_real_2,
 (cast(c.ict_pct as DOUBLE) * b.Sine2) ict_imag_2,
 (cast(c.sp99 as DOUBLE) * b.Cosine14) sp99_real_14,
 (cast(c.sp99 as DOUBLE) * b.Sine14) sp99_imag_14,
 (cast(c.sp95 as DOUBLE) * b.Cosine14) sp95_real_14,
 (cast(c.sp95 as DOUBLE) * b.Sine14) sp95_imag_14,
 (cast(c.sp90 as DOUBLE) * b.Cosine14) sp90_real_14,
 (cast(c.sp90 as DOUBLE) * b.Sine14) sp90_imag_14,
 (cast(c.sp75 as DOUBLE) * b.Cosine14) sp75_real_14,
 (cast(c.sp75 as DOUBLE) * b.Sine14) sp75_imag_14,
 (cast(c.dp99 as DOUBLE) * b.Cosine14) dp99_real_14,
 (cast(c.dp99 as DOUBLE) * b.Sine14) dp99_imag_14,
 (cast(c.dp95 as DOUBLE) * b.Cosine14) dp95_real_14,
 (cast(c.dp95 as DOUBLE) * b.Sine14) dp95_imag_14,
 (cast(c.dp90 as DOUBLE) * b.Cosine14) dp90_real_14,
 (cast(c.dp90 as DOUBLE) * b.Sine14) dp90_imag_14,
 (cast(c.dp75 as DOUBLE) * b.Cosine14) dp75_real_14,
 (cast(c.dp75 as DOUBLE) * b.Sine14) dp75_imag_14,
 (cast(c.icy_pct as DOUBLE) * b.Cosine14) icy_real_14,
 (cast(c.icy_pct as DOUBLE) * b.Sine14) icy_imag_14,
 (cast(c.ict_pct as DOUBLE) * b.Cosine14) ict_real_14,
 (cast(c.ict_pct as DOUBLE) * b.Sine14) ict_imag_14
 FROM
 mrqos_ts b
 JOIN
 mrqos_join c
 ON ( b.ts = c.ts )