USE mrqos;

drop table if exists case_view_hour;

create external table case_view_hour (
    maprule INT,
    geoname STRING,
    netname STRING,
    case_score_target INT,
    case_ra_load INT,
    case_nsd_demand DOUBLE,
    case_eu_demand DOUBLE,
    case_uniq_region INT,
    distribution STRING)

partitioned by (datestamp STRING, hour STRING)
row format delimited
fields terminated by '\t'
lines terminated by '\n'
location '/ghostcache/hadoop/data/MRQOS/case_view_hour';