USE mrqos;

drop table maprule_info;

create external table maprule_info (
    ghostip STRING,
    service STRING,
    maprule_id INT,
    maprule_name STRING,
    hits INT,
    connections INT,
    flytes BIGINT,
    bytes BIGINT,
    bytes_in BIGINT,
    cpu BIGINT,
    disk BIGINT
)

partitioned by (ts INT)
row format delimited
fields terminated by ','
lines terminated by '\n'
location '/ghostcache/hadoop/data/MRQOS/maprule_info';